[book]
authors = ["Ankitects Pty Ltd and contributors"]
language = "ja"
multilingual = false
src = "src"
title = "Ankiマニュアル"

[output.html]
git-repository-url = "https://forms.gle/jbnPepH378mVb2Sz5"
git-repository-icon = "fa-envelope"
additional-css = ["css/misc.css", "css/kbd.css"]
additional-js = ["assets/fzf.umd.js", "assets/elasticlunr.js"]

[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0